### ISSUE TITLE
Plugin not working on GoDaddy sites

### ISSUE THREAD

**Issue by RaynaNeises** [andyhqtran/Divi-100-Article-Card#19] opened 2016-06-05 20:59 UTC
### Problem:

I have installed this plug in on a couple of sites with not problem.  I have tried to install it on two GoDaddy sites and it won't work.  I spoke with tech support and they helped me install in on the server but it doesn't change the look of the blog and the menu doesn't look the same as it did on the sites in which it ran correctly.  When I installed it on the second site, it did allow me to upload it through WordPress but it cause a fatal error.  I had to be deleted the file to restore the site.

### Steps To Reproduce:
1. Install the zip file on a WP Divi theme site either through adding a Plugin or directly to the server file manager on sites hosted by GoDaddy.
2. 
3.
4.

### Additional Information:

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Reference**:

-

#### Before submitting your issue, please ensure the following:

* [ ] You have reproduced the issue using the latest code from the master branch of this repository.
* [ ] You searched Github for the issue and found no reports of the issue currently open.
* [ ] You properly formated the issue title – `Scope :: One sentence to describe the issue`.
* [ ] You have provided a detailed description of the issue.
* [ ] You have provided any/all relevant information: screenshot, screencast, ticket URL.
* [ ] You have provided the steps that one must take to reproduce the issue.

**Comment by MavenNGA** [comment] 2016-06-06 16:46
I'm having the same issue!

**Comment by andyhqtran** [comment] 2016-06-06 23:47
Duplicate of #18

**Closed by andyhqtran** 2016-06-06 23:47 UTC
