### ISSUE TITLE
Broken after latest divi update

### ISSUE THREAD

**Issue by piratephil** [andyhqtran/Divi-100-Article-Card#32] opened 2016-07-01 11:12 UTC
### Problem:
After updating divi to DiviVersion: 2.7.8 The card design breaks. The description text is displayed rather than being hidden.

<img width="1238" alt="screen shot 2016-07-01 at 12 11 33" src="https://cloud.githubusercontent.com/assets/1511359/16520013/075ad0e4-3f85-11e6-89e9-4f5d8df7a6b1.png">

### Steps To Reproduce:

1. Update Wordpress and Divi theme to latest versions.

### Additional Information:

**Divi Version**:
2.7.8

**Child Theme**:
n/a

**Device**:
n/a
**Operating System**:
OSX

**Browser**:
Chrome

**Comment by erikgeurts** [comment] 2016-07-01 11:14
Duplicate of #25 . I recommend installing the latest release of this plugin (0.0.3) and you will likely see the issue is already fixed. See https://github.com/andyhqtran/Divi-100-Article-Card/releases

**Comment by andyhqtran** [comment] 2016-07-01 22:41
@erikgeurts comment is the fix! 👍

**Closed by andyhqtran** 2016-07-01 22:41 UTC
