### ISSUE TITLE
Divi 3.0.1 breaks the formatting of the article cards.

### ISSUE THREAD

**Issue by MarleVVLL** [andyhqtran/Divi-100-Article-Card#52] opened 2016-10-04 19:27 UTC
### Problem:
I recently installed Divi 3.0.1 and the article cards have lost a large percentage of their formatting. A major issue is the excerpt which is supposed to be shown only on-hover is now visible without hovering.

### Steps To Reproduce:

1. Download Divi 3.0.1.
2. Look at a post which is affected by the article card extension.

### Additional Information:

**Divi Version**: 3.0.1

**Child Theme**: N/A

**Device**: Computer

**Operating System**: Windows 10

**Browser**: Chrome

**Screen Resolution**: 1920x1080

**Comment by SiestaLOL** [comment] 2016-10-04 20:11
I have the same problem.

**Comment by erikgeurts** [comment] 2016-10-05 05:57
Have you tried upgrading to Divi v3.0.11?

**Comment by hibagus** [comment] 2016-10-05 06:34
I am at Divi v3.0.11 right now and I have the same problem. Excerpt is visible without hovering.

**Comment by erikgeurts** [comment] 2016-10-05 06:44
I'm at Divi 3.0.11 now too, and it works just fine for me. See this screen shot with one article card hovered and one untouched:
![image](https://cloud.githubusercontent.com/assets/5102461/19103565/e42406ce-8ad7-11e6-9233-a09101ea6565.png)

**Comment by hibagus** [comment] 2016-10-05 06:48
Hi Erik,
I will try to reinstall the extension and see if it helps. I have just upgraded to 3.0.11 today.

![untitled](https://cloud.githubusercontent.com/assets/9344035/19103629/3889a6e0-8b02-11e6-8a2c-7a307b42f5a7.png)

**Comment by hibagus** [comment] 2016-10-05 07:46
It seems that reinstalling the extension does not help. So, I have decided to downgrade to Divi version 3.0.6 for a temporary fix until next release.

**Comment by tori03** [comment] 2016-10-05 07:52
Not working for me either on Divi 3.0.11. I have tried reinstalling the plugin.

**Comment by erikgeurts** [comment] 2016-10-05 07:55
Have you also checked that you're using the most recent version of the Article Cards plugin, which is Version 0.0.3?

**Comment by tori03** [comment] 2016-10-05 07:56
Yes, of course. It was already v. 0.0.3 but I downloaded it again just to make sure.

**Comment by hibagus** [comment] 2016-10-05 08:02
Yes, I am using 0.0.3 for the Article Cards plugin.

**Comment by marcopierrard** [comment] 2016-10-05 08:22
Hello,
Same problem on my site too with latest version of Divi and Article cards Plugin.
I think i know why some have the problem on their site and not others. I don't know if it's the same thing for you but on mine only the newest articles are broken (made since divi 3 ?), the others are fine.
If it can help you find where is the problem...

**Comment by tori03** [comment] 2016-10-05 09:08
That is not the case for me. All article cards are broken regardless of when the posts were created.

**Comment by MarleVVLL** [comment] 2016-10-05 21:18
After updating to Divi's 3.0.11 update, the card extension is will malfunctioning.

**Comment by pixelxcode** [comment] 2016-10-06 03:19
On 3.0.12, article card is broken. I had to disable it.

**Comment by erikgeurts** [comment] 2016-10-06 07:27
Yes, broken for me too now. I've disabled it. Too bad, and very sad that @andyhqtran doesn't seem to be be able to find the time to support this. It might be better of the responsibility for this plugin is transferred to Elegant Themes.

**Comment by tori03** [comment] 2016-10-06 13:31
The devs seem to have a fix for it over at the ET forum: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=601369

Hopefully just a matter of time before the plugin is updated.

**Comment by erikgeurts** [comment] 2016-10-06 13:56
I applied that quick fix and I can confirm it works.

**Comment by iemanuel** [comment] 2016-10-06 13:56
Divi, No Child Theme, Version: 3.0.12 -> issue appear only if you set the excerpt manually.
It works as expected if the field in post edit is empty and excerpt is auto-generated.

**Comment by erikgeurts** [comment] 2016-10-06 13:58
@iemanuel That's rather funny because in an earlier incarnation, the problem was that it didn't show the generated excerpt (if I remember correctly) and one had to set an excerpt manually to work around that.

**Comment by iemanuel** [comment] 2016-10-06 14:11
the quick fix works for now, thank you @tori03  for sharing.

**Comment by MarleVVLL** [comment] 2016-10-06 18:50
I can confirm the fix is functional on my end.

**Comment by pixelxcode** [comment] 2016-10-07 02:56
Thanks @tori03! The fix works.

**Comment by josmosis** [comment] 2016-10-07 14:27
I have had the same issue : after updating DIVI, category names overlapped excerpt on all my blog modules. As I prefer not to do things on which I do not have good control (such as code copy/paste in different areas), I prefer waiting for the plugin update. BY WHEN DO YOU THINK THAT "Article Cards" issues will UPDATE and newer version released ?

**Comment by andyhqtran** [comment] 2016-10-07 19:28
I have updated the plugin to be compability with the latest version of Divi. Please let me know if there's anymore issues with it.

You can download the latest version on the [release page](https://github.com/andyhqtran/Divi-100-Article-Card/releases).

**Comment by erikgeurts** [comment] 2016-10-08 08:08
@andyhqtran Very good! In addition to fixing this issue, the new v0.0.4 also takes care of a much looked for tweak, which is that the excerpt can now also be clicked.

**Comment by MarleVVLL** [comment] 2016-10-08 19:47
The extension now fails after I have updated Divi to 3.0.14. :(

**Comment by josmosis** [comment] 2016-10-09 08:09
Hi Andy, wonderful, the new version 0.0.4 is perfectly running and the job, the look, is really nice, better than previous 0.0.3. Thanks a lot.

**Comment by andyhqtran** [comment] 2016-10-11 22:25
@MarleVVLL could you create a separate issue for this?

**Closed** 2016-10-11 22:25 UTC
Labels: BUG

**Comment by suja223** [comment] 2018-01-22 01:29
Hi,

I just updated new divi theme v3.0.97 and I am facing the same problems.

You can check all my pages:
[http://www.divisiteexamples.com](http://www.divisiteexamples.com)
http://www.divisiteexamples.com/divi-sites-showcase/
http://www.divisiteexamples.com/free-layouts/
http://www.divisiteexamples.com/premium-layouts/
http://www.divisiteexamples.com/divi-child-themes/
http://www.divisiteexamples.com/divi-plugins/
http://www.divisiteexamples.com/divi-blog/

Thanks and Best Regards

**Comment by MarleVVLL** [comment] 2018-01-22 01:32
Suja,

**This site can’t be reached
www.divisiteexamples.com’s server IP address could not be found.
Search Google for divi site examples blog
ERR_NAME_NOT_RESOLVED**

I can't view your sites properly.

**Comment by ghost** [comment] 2018-03-20 18:03
Hello plugin does not work with previous posts in the grid, the last 3 posts work fine, and if you go to the past, they load with the old design.

Additional Information:
Divi Version: 3.0.106

Child Theme: Yes

Device: Computer

Operating System: Windows 10

Browser: Chrome

Screen Resolution: 1680x1050
